project_id            = "csye-6225-419603"
source_image_family   = "centos-stream-8"
image_name            = "centos-csye"
zone                  = "us-east4-a"
ssh_username          = "packer"
dev_deploy_image_name = "centos-csye-deploy"
network               = "default"
